
import java.awt.Dimension;

public class Menu extends javax.swing.JFrame {
    
    public Menu() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de ventas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nuevoUsuario = new javax.swing.JMenuItem();
        gestionarUsuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        nuevoProducto = new javax.swing.JMenuItem();
        gestionarProductos = new javax.swing.JMenuItem();
        actualizarStock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        nuevoCliente = new javax.swing.JMenuItem();
        gestionarClientes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        nuevaCategoria = new javax.swing.JMenuItem();
        gestionarCategorias = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        nuevaVenta = new javax.swing.JMenuItem();
        gestionarVentas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        reportesClientes = new javax.swing.JMenuItem();
        ReportesCategorias = new javax.swing.JMenuItem();
        reportesProductos = new javax.swing.JMenuItem();
        reportesUsuarios = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        verHistorial = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        cerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(150, 50));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMenu1.setText("Usuario");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(150, 50));

        nuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        nuevoUsuario.setText("Nuevo Usuario");
        nuevoUsuario.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu1.add(nuevoUsuario);

        gestionarUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        gestionarUsuarios.setText("Gestionar Usuarios");
        gestionarUsuarios.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu1.add(gestionarUsuarios);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenu2.setText("Producto");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        nuevoProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        nuevoProducto.setText("Nuevo Producto");
        nuevoProducto.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu2.add(nuevoProducto);

        gestionarProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gestionarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        gestionarProductos.setText("Gestionar Productos");
        gestionarProductos.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu2.add(gestionarProductos);

        actualizarStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actualizarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        actualizarStock.setText("Actualizar Stock");
        actualizarStock.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu2.add(actualizarStock);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenu3.setText("Cliente");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 50));

        nuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        nuevoCliente.setText("Nuevo Cliente");
        nuevoCliente.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu3.add(nuevoCliente);

        gestionarClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gestionarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        gestionarClientes.setText("Gestionar Clientes");
        gestionarClientes.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu3.add(gestionarClientes);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenu4.setText("Categoria");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 50));

        nuevaCategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nuevaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        nuevaCategoria.setText("Nueva Categoria");
        nuevaCategoria.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu4.add(nuevaCategoria);

        gestionarCategorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gestionarCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        gestionarCategorias.setText("Gestionar Categorias");
        gestionarCategorias.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu4.add(gestionarCategorias);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        jMenu5.setText("Facturar");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(150, 50));

        nuevaVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        nuevaVenta.setText("Nueva Venta");
        nuevaVenta.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu5.add(nuevaVenta);

        gestionarVentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gestionarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        gestionarVentas.setText("Gestionar Ventas");
        gestionarVentas.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu5.add(gestionarVentas);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        jMenu6.setText("Reportes");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));

        reportesClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reportesClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        reportesClientes.setText("Reportes Clientes");
        reportesClientes.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu6.add(reportesClientes);

        ReportesCategorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ReportesCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        ReportesCategorias.setText("Reportes Categorias");
        ReportesCategorias.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu6.add(ReportesCategorias);

        reportesProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reportesProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        reportesProductos.setText("Reportes Productos");
        reportesProductos.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu6.add(reportesProductos);

        reportesUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reportesUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        reportesUsuarios.setText("Reportes Usuarios");
        reportesUsuarios.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu6.add(reportesUsuarios);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        jMenu7.setText("Historial");
        jMenu7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(150, 50));

        verHistorial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        verHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        verHistorial.setText("Ver Historial");
        verHistorial.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu7.add(verHistorial);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu8.setText("Cerrar Sesion");
        jMenu8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(200, 50));

        cerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        cerrarSesion.setText("Cerrar Sesion");
        cerrarSesion.setFocusable(true);
        cerrarSesion.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu8.add(cerrarSesion);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ReportesCategorias;
    private javax.swing.JMenuItem actualizarStock;
    private javax.swing.JMenuItem cerrarSesion;
    private javax.swing.JMenuItem gestionarCategorias;
    private javax.swing.JMenuItem gestionarClientes;
    private javax.swing.JMenuItem gestionarProductos;
    private javax.swing.JMenuItem gestionarUsuarios;
    private javax.swing.JMenuItem gestionarVentas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem nuevaCategoria;
    private javax.swing.JMenuItem nuevaVenta;
    private javax.swing.JMenuItem nuevoCliente;
    private javax.swing.JMenuItem nuevoProducto;
    private javax.swing.JMenuItem nuevoUsuario;
    private javax.swing.JMenuItem reportesClientes;
    private javax.swing.JMenuItem reportesProductos;
    private javax.swing.JMenuItem reportesUsuarios;
    private javax.swing.JMenuItem verHistorial;
    // End of variables declaration//GEN-END:variables
}
